- name: Install MySQL server on RHEL 9
  dnf:
    name: mysql
    state: present
  become: yes

- name: Ensure MySQL is started and enabled
  service:
    name: mysqld
    state: started
    enabled: yes